const GameUI={
init(){document.querySelectorAll(".bottom-nav button").forEach(b=>b.addEventListener("click",()=>{GameState.data.view=b.dataset.view;this.render()}));document.getElementById("saveBtn").onclick=()=>{GameState.save();this.toast("Progress saved")};this.render()},
render(){document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===GameState.data.view));document.getElementById("evidenceCount").textContent=GameState.data.inventory.length;const s=document.getElementById("screen");const v=GameState.data.view;if(v==="evidence")return this.evidence();if(v==="phone")return this.phone();if(v==="notes")return this.notes();this.caseView()},
caseView(){const s=document.getElementById("screen");if(GameState.data.chapter===1){s.innerHTML='<span class="label">CASE H-20 · OPEN</span><h1>Something is missing.</h1><p class="muted">A device was recovered with almost everything wiped. One conversation survived.</p><div class="card"><div class="meta"><span>STATUS</span><span>INVESTIGATION 01</span></div><h2>The first message</h2><p>A message from an unknown number tells you not to start with the obvious thing.</p><button class="btn primary" onclick="Phone.open()">Read recovered messages</button></div><div class="card"><span class="label">OBJECTIVE</span><h3>Find the first piece of evidence.</h3><p class="tiny">The answer is somewhere in the scene.</p></div>}else{s.innerHTML='<span class="label">CASE H-20 · ACTIVE</span><h1>The pattern is deliberate.</h1><p class="muted">The first code opened a fictional address fragment. Whatever this is, it is becoming personal.</p><div class="card"><div class="meta"><span>CHAPTER 02</span><span>UNLOCKED</span></div><h2>The location</h2><p>17 Rue Al Qamar, Hay Al Wifaq. A place that should mean something.</p><button class="btn primary" onclick="GameUI.modal('<span class=&quot;label&quot;>NEXT INVESTIGATION</span><h2>Location analysis</h2><p>The next chapter will use the personal information you provide for the case.</p><button class=&quot;btn&quot; onclick=&quot;GameUI.closeModal()&quot;>Close</button>')">Inspect evidence</button></div><div class="card"><span class="label">NEXT</span><h3>Connect the location to the people involved.</h3></div>'}},
scene(){const s=document.getElementById("screen");s.innerHTML='<span class="label">LOCATION · UNKNOWN ROOM</span><h1>Look carefully.</h1><p class="muted">Most objects are irrelevant. A few are not.</p><div class="scene"><div class="object clock" onclick="Puzzles.sceneClue(\'clock\')">21:14</div><div class="object bag" onclick="Puzzles.sceneClue(\'bag\')">BAG</div><div class="object notebook" onclick="Puzzles.sceneClue(\'notebook\')">NOTEBOOK</div><div class="object phoneObj" onclick="Puzzles.sceneClue(\'phone\')">PHONE</div><div class="desk"></div></div><div class="card"><span class="label">TIP</span><p class="tiny">Not every clickable object is useful.</p></div>'},
evidence(){const s=document.getElementById("screen");let html='<span class="label">EVIDENCE</span><h1>Recovered items</h1>';if(!GameState.data.inventory.length)html+='<p class="muted">Nothing recovered yet.</p>';else{html+='<div class="evidence-grid">';GameState.data.inventory.forEach(id=>{const e=Evidence.items[id];html+='<div class="card clickable" onclick="Evidence.open(\''+id+'\')"><span class="tag">'+e.type+'</span><h3>'+e.title+'</h3><p class="tiny">'+e.text+'</p></div>'});html+='</div>'}if(GameState.has("photo")&&GameState.has("note"))html+='<div class="card"><span class="label">NEW LEAD</span><h2>Locked file</h2><p class="muted">The evidence suggests a four-digit access code.</p><button class="btn primary" onclick="Puzzles.openCode()">Attempt access</button></div>';s.innerHTML=html},
phone(){document.getElementById("screen").innerHTML='<span class="label">DEVICE</span><h1>Recovered phone</h1><p class="muted">Partial access has been restored.</p><div class="card"><button class="btn primary" onclick="Phone.open()">Open device</button></div>'},
notes(){document.getElementById("screen").innerHTML='<span class="label">CASE NOTES</span><h1>Investigator notes</h1><div class="card"><p>'+((GameState.has("note"))?'FIRST / AFTER / QUIET / LOOK.':'No notes recorded yet.')+'</p></div>'},
modal(html){const m=document.getElementById("modal");m.innerHTML='<div class="modal-box"><button class="close" onclick="GameUI.closeModal()">×</button>'+html+'</div>';m.classList.remove("hidden")},
closeModal(){document.getElementById("modal").classList.add("hidden")},
toast(t){const x=document.createElement("div");x.textContent=t;x.style='position:fixed;top:74px;left:50%;transform:translateX(-50%);z-index:30;background:#20252b;border:1px solid #3a424b;border-radius:8px;padding:9px 13px;font-size:12px';document.body.appendChild(x);setTimeout(()=>x.remove(),1400)}
};document.addEventListener("DOMContentLoaded",()=>GameUI.init());