const Puzzles={
openFirst(){GameUI.closeModal();GameUI.scene()},
sceneClue(id){
 if(id==="clock"){Evidence.add("photo");GameState.solve("scene-clock");GameState.note("21:14 appears in both the room and the photograph.");GameUI.modal('<span class="label">CLUE 01</span><h2>21:14</h2><p>The room clock and recovered photograph agree to the minute.</p><button class="btn primary" onclick="GameUI.closeModal()">Keep clue</button>')}
 if(id==="phone"){Evidence.add("phone");GameState.solve("scene-phone");GameUI.modal('<span class="label">DEVICE RECOVERED</span><h2>Partial access</h2><p>One conversation survived. The rest of the phone is protected.</p><button class="btn primary" onclick="Phone.open()">Open phone</button>')}
 if(id==="notebook"){Evidence.add("note");GameState.solve("scene-note");GameState.note("FIRST / AFTER / QUIET / LOOK");GameUI.modal('<span class="label">CLUE 02</span><h2>Four words</h2><p>FIRST / AFTER / QUIET / LOOK. It reads like an instruction.</p><button class="btn primary" onclick="GameUI.closeModal()">Keep evidence</button>')}
 if(id==="bag"){GameState.solve("scene-bag");GameUI.modal('<span class="label">NOTHING</span><h2>Just a bag.</h2><p>Useful reminder: not every object is evidence.</p><button class="btn" onclick="GameUI.closeModal()">Continue</button>')}
},
openCode(){if(!GameState.has("photo")||!GameState.has("note"))return GameUI.modal('<h2>LOCKED</h2><p class="muted">You need the photograph and the four-word note.</p>');GameUI.modal('<span class="label">LOCKED FILE</span><h2>Four digits</h2><p>The instruction says to look at what came first. The photograph gives you the time.</p><input id="codeInput" inputmode="numeric" maxlength="4" placeholder="••••"><button class="btn primary" onclick="Puzzles.checkCode()">Unlock</button>')},
checkCode(){const v=document.getElementById("codeInput")?.value;if(v!=="2114")return GameUI.modal('<h2>Not enough.</h2><p class="muted">The evidence does not support that sequence.</p><button class="btn" onclick="Puzzles.openCode()">Try again</button>');GameState.solve("file-2114");GameState.data.chapter=2;GameState.unlock("profile");GameState.unlock("photos");GameState.unlock("notes");Evidence.add("profile");GameState.note("The first lock used 21:14.");GameState.save();GameUI.closeModal();GameUI.render()},
profilePuzzle(){GameUI.modal('<span class="label">PERSONAL PROFILE</span><h2>Reconstruct the description</h2><p>The message gave three fragments: a paw, a coin, and something red. Choose the three details that fit.</p><div class="choice-grid"><button class="btn" onclick="Puzzles.profilePick(\'cats\')">CAT</button><button class="btn" onclick="Puzzles.profilePick(\'money\')">MONEY</button><button class="btn" onclick="Puzzles.profilePick(\'strawberry lipstick\')">STRAWBERRY LIPSTICK</button><button class="btn" onclick="Puzzles.profilePick(\'heat\')">HEAT</button><button class="btn" onclick="Puzzles.profilePick(\'cooking\')">COOKING</button><button class="btn" onclick="Puzzles.profilePick(\'chores\')">CHORES</button></div>')},
profilePick(value){const picks=GameState.data.flags.profilePicks||[];if(!picks.includes(value))picks.push(value);GameState.data.flags.profilePicks=picks;GameState.save();if(picks.length<3)return GameUI.toast(picks.length+"/3 matched");const correct=["cats","money","strawberry lipstick"].every(x=>picks.includes(x));if(!correct){GameState.data.flags.profilePicks=[];GameState.save();return GameUI.modal('<h2>Reset.</h2><p class="muted">The three fragments must describe things she likes, not things she avoids.</p><button class="btn" onclick="Puzzles.profilePuzzle()">Rebuild</button>')}GameState.solve("profile-puzzle");GameState.unlock("files");GameState.data.chapter=3;GameState.note("The three personal fragments resolve to cats, money and strawberry lipstick.");GameState.save();GameUI.closeModal();GameUI.render()},
familyPuzzle(){GameUI.modal('<span class="label">FAMILY / 05</span><h2>Order the three sisters</h2><p>The note says: <strong>not the parents, not the subject, youngest to oldest.</strong> Use the ages in the index.</p><div class="choice-grid"><button class="btn" onclick="Puzzles.familyAnswer(\'ZMO\')">Zineb → Meriem → Oumaima</button><button class="btn" onclick="Puzzles.familyAnswer(\'OMZ\')">Oumaima → Meriem → Zineb</button><button class="btn" onclick="Puzzles.familyAnswer(\'MZO\')">Meriem → Zineb → Oumaima</button></div>')},
familyAnswer(answer){if(answer!=="ZMO")return GameUI.modal('<h2>Wrong order.</h2><p class="muted">Check the ages: 26, 27, 29.</p><button class="btn" onclick="Puzzles.familyPuzzle()">Back</button>');Evidence.add("family");GameState.solve("family-puzzle");GameState.data.chapter=4;GameState.unlock("relationship");GameState.unlock("internship");GameState.note("The sisters order is Zineb (26), Meriem (27), Oumaima (29).");GameState.save();GameUI.closeModal();GameUI.render()},
connectionPuzzle(){GameUI.modal('<span class="label">CONNECTION TEST</span><h2>Follow the chain</h2><p>The internship record says the workplace is connected through a sister. The relationship file says Zaki is the subject\'s partner. Which statement is supported?</p><div class="choice-grid"><button class="btn" onclick="Puzzles.connectionAnswer(false)">The workplace is Hiba's own business.</button><button class="btn" onclick="Puzzles.connectionAnswer(true)">The workplace is connected through Hiba's sister and her sister's boyfriend.</button><button class="btn" onclick="Puzzles.connectionAnswer(false)">The workplace is unrelated to the family.</button></div>')},
connectionAnswer(correct){if(!correct)return GameUI.toast("That conclusion is not supported.");Evidence.add("internship");Evidence.add("relationship");GameState.solve("connection-puzzle");GameState.data.chapter=5;GameState.unlock("final");GameState.note("The case connects Hiba, her sister's workplace connection, and Zaki.");GameState.save();GameUI.closeModal();GameUI.render()},
finalPuzzle(){GameUI.modal('<span class="label">SEALED FILE</span><h2>Why 26 November?</h2><p>The file asks for the date behind the case. Enter it as DDMMYYYY.</p><input id="finalInput" inputmode="numeric" maxlength="8" placeholder="DDMMYYYY"><button class="btn primary" onclick="Puzzles.checkFinal()">Open FILE 020</button>')},
checkFinal(){const v=document.getElementById("finalInput")?.value;if(v!=="26112006")return GameUI.toast("The date does not match the recovered record.");Evidence.add("final");GameState.solve("final-date");GameState.flag("ending",true);GameState.save();GameUI.closeModal();GameUI.render()}
};